name: Django EC2 CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # This script runs INSIDE your EC2
          script: |
            cd ~/SCSP
            
            # 1. Update code
            git pull origin main
            
            # 2. Sync dependencies
            source venv/bin/activate
            pip install -r requirements.txt
            
            # 3. Database & Static files
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput
            
            # 4. Restart Application Server
            sudo systemctl restart gunicorn